### ISSUE TITLE
Removal of All Analytical Tracking From .org

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#1419]
Independent of the discussion regarding the help screen proxy, I am proposing that a formal motion is raised for the removal of analytical tracking from all Joomla owned domains.  Given that the data is not actually used in any meaningful way by the Joomla Project, and the failure of the Compliance Team to create a solution that is compliant with applicable laws and regulations (which has also caused confusion on the allowed content on .org and the removal of pages whose content was a recognition of contributors) the only practical solution that can be implemented in a timely manner while creating the least amount of effort for all parties is the flat out removal of all analytical tracking scripts.

**Comment by sebastienlapoux** [comment]
Thanks @mbabker . Has the majority of j.org websites are using not only GA service, I don't understand what you will fix by removing GA.

**Comment by mbabker** [comment]
I am not referring only to the use of Google Analytics, but rather all tracking mechanisms.

**Comment by sebastienlapoux** [comment]
Not possible without huge consequences @mbabker such as for Youtube service or Google Ads... IMO no choice to manage really the compliance of j.org website even if consequences are huge too such as to have lot less ads (and so money) displayed for all users who will not accept cookies.

**Comment by mbabker** [comment]
I don't really care who's problem it is at this point.  One team's failure to act should not cause the entirety of an organization to be left open for legal compliance matters.

**Comment by mbabker** [comment]
My apologies for not taking action on something sooner while waiting for the Compliance Team, who has regularly reported that they were working on a solution, to deliver said solution.  Since it seems that solution is still nowhere near being ready for delivery, as the responsible webmaster for a number of domains I have made the decision to remove the risk involved in the use of Google Analytics due to its tracking nature by flat out removing the integration.

**Comment by mbabker** [comment]
I do like though that I decide to take action and suddenly people are pissed off that I actually came up with a solution to the problem and implemented it.

If you want to single me out for screwing something up between May 2018 and October 2019 by not acting on the analytics issue sooner, then you also need to do the responsible thing and blame every individual who has been a member of the Compliance Team from May 2018 to present for the same thing.

Until their work has reached a point where it is production ready, my changes to the various subdomains will stand.

**Comment by conconnl** [comment]
Having opinions is one thing.
Proposing solutions is another thing.

Taking actions on systems which are in the responsibility of a certain department, without involving them is just plainly wrong. Especially when you tell everybody that you have quit the community, stopped doing anything. I even spend all my time and effort to help you move on and handover the work to the rightful departments and members.

Sorry, but your behavior is just a "Fuck you" message to everything what I have been trying to do for you and support you with. You have zero reason that if someone triggered an issue again and get some support from others to discuss options and make a possible decision, to just behave like this.

**Comment by brianteeman** [comment]
@mbabker I understand (and share) your frustration at waiting 2 years for the cookie script to be implemented but you are out of order in taking that action

**Comment by mbabker** [comment]
Then what else am I supposed to do?  Elisa wanted GTM gone on a subdomain, it's gone.  I also acted on the Compliance Team's failure to deliver, and OSM's failure to hold anyone accountable for the failure to deliver, by beginning the removal of GTM from properties using the same justification for removal from the help proxy.  Nobody else seems to want to take timely action, I did.

**Comment by brianteeman** [comment]
> Then what else am I supposed to do? 

Nothing

**Comment by sebastienlapoux** [comment]
@brianteeman and @mbabker can you please give me each of you 2 sites loading web services and respecting the GDPR cookie compliance?

**Comment by brianteeman** [comment]
What does that have to do with anything?

**Comment by mbabker** [comment]
Anyone git savvy can undo the changes I made.  I stand by my decision, even if out-of-line for how it was taken.

**Comment by mbabker** [comment]
> @brianteeman and @mbabker can you please give me each of you 2 sites loading web services and respecting the GDPR cookie compliance?

The only publicly sharable website I have with such controls in place is the one I have listed in your directory.

**Comment by sebastienlapoux** [comment]
About the fact that the topic to be cookie compliant is very complex and that 2 years after the GDPR very very few sites are able to respect it. Consequences to be cookie compliant are very huge for a lot of websites and bring the fact to rethink the economic model. I think it's the case for J.org websites (if ads are staying so important for financial aspect) and I think no urgency even if this topic need to move forward.

**Comment by mbabker** [comment]
I don't deal with websites which have advertisements such as those that exist throughout `joomla.org`, in fact the site where I have implemented cookie control measures only has Google Analytics (it doesn't even have sessions like the Joomla software mandates) and that is configured in the simplest of ways:

```javascript
ga('create', 'UA-XXX-X', 'auto');
ga('set', 'forceSSL', true);

if (this.hasConsented()) {
    ga('require', 'displayfeatures');
    ga('set', 'anonymizeIp', undefined);
} else {
    ga('set', 'displayFeaturesTask', null);
    ga('set', 'anonymizeIp', true);
}

ga('send', 'pageview');
```

**Comment by sebastienlapoux** [comment]
Thanks @mbabker . Your website has a nice working cookie banner. You're using for video Youtube service with the domain www.youtube-nocookie.com which is not warranty at all that Youtube is not saving personal data. In fact it's totally false because when you run the video on your site the visitor is tracked personally by Youtube. Currently your site is not GDPR compliant. The Youtube code must be loaded by your site only after his consent.

**Comment by jeckodevelopment** [comment]
The ONLY source of money for the Joomla Project is selling sponsorship and advertising.
If you drop analytics, you won't have the numbers to provide to potential sponsors or advertisers, so you won't have sponsorship agreements.

I remember very well that people from Compliance Team asked your review on the cookie script and had hard times to reach you @mbabker and to have a feedback from you. 
I'm very disappointed by this kind of reactions. 
It's disappointing when people who contribute are defamed publicly in this way.
The cookie script was pending your review and approval and yes, it wasn't final.

Are you going to cover with your salary the lack of income from sponsorship since we can't provide analytics numbers?

Why do you act without consulting anyone and taking unilaterally decisions that you are not supposed to take?

I have huge respect for you as person and experience, but, this is not the right way to act.

**Comment by sebastienlapoux** [comment]
> in fact the site where I have implemented cookie control measures only has Google Analytics (it doesn't even have sessions like the Joomla software mandates) and that is configured in the simplest of ways

Google Analytics currently is not recognized as to be GDPR compliant in Europe, because only the last 3 digits of IP are anonymized. It requires at least the last 6 digits to be sure that you can just know the country of a visitor (which is ok to say it's not a personal data) like Matomo is proposing. And no mean to be sure about what's is doing Google about IP as nothing about this is contractual.
Another point is concerning the duration of cookies, any cookies which have a duration different than the session can help about profiling method to know who you're. It's related to the notion in GA about unique user. You can avoid this into GA by forcing cookie duration to the session time. In this case no more difference into GA between user and unique user.

**Comment by brianteeman** [comment]
The UK is still in Europe are you suggesting that you know better than the Uk Government about GA and Youtube?

https://www.gov.uk/help/cookies

**Comment by mbabker** [comment]
I have reverted the changes I have made.

In order to ensure a positive and safe working environment for members of the Joomla Project, I would like to ask that @jeckodevelopment @conconnl @Radek-Suski @marcodings in their roles as team leaders and members of the organizational board of directors ensure that the following items are actioned as soon as possible:

- [ ] I demand that organizational membership to the @joomla, @joomla-projects, @joomla-extensions, @joomla-framework, or any other Joomla and/or Open Source Matters, Inc., owned GitHub organizations be terminated immediately (to include any write and/or administrative access to individual properties)
    - [ ] Upon completion of this task, in order to ensure that the project space remains a positive and safe environment, I should be administratively banned from interactions with all repositories falling under this scope
- [ ] I demand that any administrative user accounts on any `joomla.org`, `opensourcematters.org`, or any other Joomla and Open Source Matters, Inc., owned domains be terminated immediately
    - [ ] Upon completion of this task, in order to ensure that the project space remains a positive and safe environment, any non-administrative user accounts should also be banned from use on these domains
- [ ] I demand that any server level accesses to any `joomla.org`, `opensourcematters.org`, or any other Joomla and Open Source Matters, Inc., owned domains be terminated immediately
- [ ] I demand that my individual account with Glip be terminated effective immediately
- [ ] I demand access to all Joomla and Open Source Matters, Inc., integrations with Google, EXCEPT FOR GOOGLE MAIL, be terminated immediately
- [ ] I demand that any administrative roles and/or write level accesses to Crowdin be terminated effective immediately
- [ ] I demand that any administrative accesses to any social media integrations be terminated immediately

**Comment by jeckodevelopment** [comment]
@mbabker nobody said that you should leave the organization, NEVER.
If you want to cease your accounts and permissions, that can be done. 

I just want you to realize that the unilaterally decision that you have taken (and then reverted) would have had important financial impacts on the Project.

The fact that you are keeping your permissions in the organization at a certain level is a sign of trust that the Board and the Project as such has always had in you, Michael.
Otherwise your permissions and accounts would have been removed a while ago, when you left the teams.

Is it necessary to start a useless drama each and every month? for each and every topic?

**Comment by mbabker** [comment]
Oh, I'm sorry, I thought I was making a positive contribution to the ecosystem by requesting that an individual who is constantly deemed toxic, trouble making, and a source of drama, to have his ability to interact with the ecosystem restricted.  I know you might not see the problem, but there have been more than enough occasions where it has been deemed that I am a blocker to progress that I figured removal of that blocker would only be a good thing.  Guess I was wrong, again.

`/sarcasm`

**Comment by sebastienlapoux** [comment]
@brianteeman  this website is a nice example, thank you! Because for me it's very close to be fully compliant, there is only the point of the IP which can bring discussion. So if all j.org websites are like this it will be a lot more acceptable.
All other aspect are very well respected by this website such as the duration of GA cookies set to session lifetime or the display of youtube video only after your consent such as on https://www.gov.uk/guidance/help-and-support-for-self-assessment
Have a look on innio website to find a nice example too.

**Comment by jeckodevelopment** [comment]
> 
> 
> Oh, I'm sorry, I thought I was making a positive contribution to the ecosystem by requesting that an individual who is constantly deemed toxic, trouble making, and a source of drama, to have his ability to interact with the ecosystem restricted. I know you might not see the problem, but there have been more than enough occasions where it has been deemed that I am a blocker to progress that I figured removal of that blocker would only be a good thing. Guess I was wrong, again.
> 
> `/sarcasm`

Michael, you know the consideration I've for you. And i'm not the only one who always saw the positive stuff you did and continue doing for Joomla. Come on!

You are in the position and you have the needed knowledge to advice on the proper solution to this long-standing issue that is not `let's drop completely Google Tag Manager` , but it's `let's see what is missing to make the Cookie Script happen and solve this issue`.

I believe that you can make positive contribution, as you almost always.

**Comment by jeckodevelopment** [comment]
By the way, there are 3 commits that made the work on the Cookie Script almost done:

- https://github.com/joomla/volunteers.joomla.org/commit/fd110a2b615f61ede355c3ccfa794566dbd946f5
- https://github.com/joomla/volunteers.joomla.org/commit/d6606908ab641c33c59b753fab9838d519fd4969
- https://github.com/joomla/volunteers.joomla.org/commit/71891f4ea61df36ba22360bc0e4eb0f4008876d3

There should be a Pull Request and then it can be checked and implemented.
Any help is more than welcome and highly appreciated. Thanks

**Comment by brianteeman** [comment]
@jeckodevelopment  help where? where is the code that is just the site repo or am I missing something

@sebastienlapoux  a very different approach is taken in france where they appear to have no problem with tracking cookies
https://www.france.fr/fr/infos/gestion-des-cookies
and in Germany where there is no request for consent at all before the cookies are set AND where there is no use of the youtube-nocookie domain or the double click to play video which I also see people insist upon
https://www.deutschland.de/en/data-protection-statement

**Comment by sebastienlapoux** [comment]
> @sebastienlapoux a very different approach is taken in france where they appear to have no problem with tracking cookies

No Brian. France.fr such as the DE website are just private websites and not "gov" website.
You can look in France https://www.economie.gouv.fr/ or https://www.interieur.gouv.fr/ (better concerning cookie) but like I said some of them are respecting, some of them are close, some of them are not. Cnil.fr yes.

**Comment by sebastienlapoux** [comment]
Have a look in your country about the 10 (or 20) biggest websites and let me know which one is respecting the GDPR.

**Comment by jeckodevelopment** [comment]
@brianteeman apologies, i provided the wrong links.

**cookiecontrol.js** : https://github.com/joomla/volunteers.joomla.org/blob/feature/gdpr/www/templates/joomla/js/cookiecontrol.js

**index.php** (contains required parts for the cookiescript): https://github.com/joomla/volunteers.joomla.org/blob/feature/gdpr/www/templates/joomla/index.php

**template.php** (contains all settings for J!Properties): https://github.com/joomla/volunteers.joomla.org/blob/feature/gdpr/www/templates/joomla/helpers/template.php

**Comment by brianteeman** [comment]
They might not be the government web sites but they are the primary web sites for their respective countries. If you really believe that they are not respecting the GDPR there is nothing I can do about it. 

My point from the beginning was to question if the request from @coolcat-creations was really required and wondering why not one other person had raised it - including the dedicated team of experts created for this.

Is joomla really going to be held to a higher standard than as you yourself point out the largest web sites in Europe do not.?

**Comment by brianteeman** [comment]
@jeckodevelopment sorry but I am not able to do a code review based on the raw files with no history or explanation

**Comment by sebastienlapoux** [comment]
>  but they are the primary web sites

No they are not primary websites (first time I'm visiting them!), just standard (small) private websites which are mainly not GDPR compliant. 

- https://www.alexa.com/topsites/countries/FR
- https://www.alexa.com/topsites/countries/GB (are they following the GDPR???)

For your other comment, IMO I already answered, all this is new and not mature, every months we can see more websites compliant but it's very slow because very difficult. IMO it's the same for ALL european countries.
Have a look on the uk website that you're using every day and let me know if they are compliant... I don't know a huge news website respecting really the GDPR because an issue about their economic model (such as for j.org)...

**Comment by coolcat-creations** [comment]
Just because other websites are not secure, we still should aim for high security, just because other websites are not accessible, we should aim for accessibility, just because other websites have bad usability, we should aim for better usability.
So just because other websites are not compliant, we should aim for to be compliant.

I never questioned an issue raised by you @brianteeman just because you were the only one taking care of it. In a respectful way I thank you in advance for an equal collaboration.

**Comment by mbabker** [comment]
Close.  Money talks.  Here's hoping the compliance team completes their deliverables in a timely manner.
